Repository meshery/meshery-istio, pull requests merged in 2021-09, with the labels that each got.

#270 [CI] Upgrade golang version in Docker builder stage
  Dockerfile
Labels: chore, area/ci

#272 [CI] update pattern glob
  .github/workflows/error-ref-publisher.yaml
Labels: area/ci, component/patterns

#275 added make test
  Makefile
Labels: area/tests

#274 [build] nodejs compatible base img
  .github/workflows/ci.yml
  Dockerfile
Labels: area/ci

#280 add label commenter workflow
  .github/label-commenter-config.yml
  .github/workflows/label-commenter.yml
Labels: chore, area/ci
