Repository meshery/meshery-istio, pull requests merged in 2021-12, with the labels that each got.

#301 how to fix a misused meshkit logger
  istio/sample_apps.go
Labels: chore

#299 Customizing URL and Method of dynamic component generation through environmental variables
  main.go
Labels: area/lifecycle

#318 Seperate e2e test for addons
  .github/install/deploywithaddons.yaml
  .github/workflows/e2etest-servicemeshandaddon.yaml
  .github/workflows/e2etest-servicemeshinstall.yaml
Labels: area/tests

#340 [Chore] misspelling of "adapter"
  main.go
Labels: chore

#344 Edit date syntax to print with SHA
  .github/workflows/e2etest-servicemeshandaddon.yaml
  .github/workflows/e2etest-servicemeshinstall.yaml
Labels: area/ci

#345 [CI] Remove $ in e2e test workflow
  .github/workflows/e2etest-servicemeshandaddon.yaml
Labels: area/ci, area/tests

#342 [Chore] Move position and verbiage registration log message
  main.go
Labels: chore, component/patterns
