Repository meshery/meshery-istio, pull requests merged in 2021-07, with the labels that each got.

#248 [CI] Workflow to generate Pattern components
  .github/.env
  .github/workflows/update-oam-defs.yml
Labels: area/ci, component/patterns

#250 changed istio apis
  istio/oam/register.go
Labels: component/patterns

#255 [CI] add error code utility runner workflows
  .github/workflows/error-ref-publisher.yaml
  .gitignore
  Makefile
  errorutil_analyze_errors.json
  errorutil_analyze_summary.json
  errorutil_errors_export.json
  helpers/component_info.json
Labels: area/ci
