Repository meshery/meshery-istio, pull requests merged in 2021-11, with the labels that each got.

#308 Fix the gosec-307
  istio/install.go
Labels: security

#285 removed extra metdata from pre-generated components
  .github/workflows/update-oam-defs.yml
Labels: hacktoberfest

#313 E2etests
  .github/install/deploy.yaml
  .github/workflows/e2etest.yaml
Labels: area/tests

#303 Slack notification
  .github/workflows/slack.yml
Labels: chore
